greenery:

  outputs:
    dbt_slothpete_practice:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    dbt_slothpete_practice_prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_slothpete_practice_bigquery:
      type: bigquery
      method: service-account
      project: dataengineercafe
      dataset: dbt_zkan
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/YOUR-KEYFILE.json
      location: asia-southeast1

    dbt_slothpete_prod_bigquery:
      type: bigquery
      method: service-account
      project: dataengineercafe
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/YOUR-KEYFILE.json
      location: asia-southeast1

  target: dbt_slothpete_practice_bigquery